"""add domain to organization

Revision ID: 51912bcd7430
Revises: 63e81e7f1a85
Create Date: 2025-10-14 12:42:23.776426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51912bcd7430'
down_revision: Union[str, Sequence[str], None] = '63e81e7f1a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('domain', sa.String(), nullable=False))
    op.create_index(op.f('ix_organizations_domain'), 'organizations', ['domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_domain'), table_name='organizations')
    op.drop_column('organizations', 'domain')
    # ### end Alembic commands ###
