"""Task Creator ID

Revision ID: 9fd288900076
Revises: 5928664792f3
Create Date: 2025-10-13 05:49:47.504477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd288900076'
down_revision: Union[str, Sequence[str], None] = '5928664792f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_by_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_tasks_created_by_id'), 'tasks', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_created_by_id'), table_name='tasks')
    op.drop_column('tasks', 'created_by_id')
    # ### end Alembic commands ###
